package io.jclaw.tools.security;

import io.jclaw.core.tool.ToolContext;
import io.jclaw.core.tool.ToolDefinition;
import io.jclaw.core.tool.ToolProfile;
import io.jclaw.core.tool.ToolResult;
import io.jclaw.tools.ToolCatalog;

import java.util.Map;
import java.util.Set;

/**
 * Validates identity by verifying a signature of the challenge nonce.
 *
 * <ul>
 *   <li><b>LOCAL</b> — verifies HMAC signature against session's shared secret</li>
 *   <li><b>HTTP_CLIENT</b> — sends the locally-computed signature to the MCP server for verification</li>
 *   <li><b>ORCHESTRATED</b> — verifies locally or passes through the MCP server's verification result</li>
 * </ul>
 */
public class VerifyIdentityTool extends AbstractSecurityTool {

    private static final String INPUT_SCHEMA = """
            {
              "type": "object",
              "properties": {
                "handshakeId": {
                  "type": "string",
                  "description": "The handshake session ID"
                },
                "method": {
                  "type": "string",
                  "description": "Verification method: 'HMAC-SHA256' or 'JWT'"
                },
                "credential": {
                  "type": "string",
                  "description": "The signed credential (HMAC signature or JWT token)"
                },
                "serverVerified": {
                  "type": "boolean",
                  "description": "Verification result from MCP server (ORCHESTRATED mode only)"
                }
              },
              "required": ["handshakeId", "method", "credential"]
            }""";

    private final HandshakeHttpClient httpClient;

    public VerifyIdentityTool(CryptoService cryptoService, HandshakeSessionStore sessionStore,
                              SecurityHandshakeProperties properties, HandshakeHttpClient httpClient) {
        super(new ToolDefinition(
                "security_verify_identity",
                "Verify client identity by validating HMAC signature or JWT against the session's shared secret.",
                ToolCatalog.SECTION_SECURITY,
                INPUT_SCHEMA,
                Set.of(ToolProfile.FULL)
        ), cryptoService, sessionStore, properties);
        this.httpClient = httpClient;
    }

    @Override
    protected ToolResult doExecute(Map<String, Object> parameters, ToolContext context) throws Exception {
        String handshakeId = requireParam(parameters, "handshakeId");
        String method = requireParam(parameters, "method");
        String credential = requireParam(parameters, "credential");

        return switch (mode()) {
            case LOCAL -> executeLocal(handshakeId, method, credential);
            case HTTP_CLIENT -> executeHttpClient(handshakeId, method, credential);
            case ORCHESTRATED -> executeOrchestrated(handshakeId, method, credential, parameters);
        };
    }

    private ToolResult executeLocal(String handshakeId, String method, String credential) {
        HandshakeSession session = sessionStore.require(handshakeId);

        if (session.getChallengeNonce() == null) {
            return new ToolResult.Error("No challenge has been issued for this session");
        }
        if (session.getSharedSecret() == null) {
            return new ToolResult.Error("Key exchange has not been completed for this session");
        }

        boolean verified;
        String details;

        if (credential != null && credential.startsWith("local-ref:")) {
            // LOCAL mode auto-verification: the credential is a reference token
            // generated by ChallengeResponseTool. Recompute the expected token
            // and compare to verify the LLM passed through the value unchanged.
            String hmac = cryptoService.hmacSign(session.getSharedSecret(), session.getChallengeNonce());
            String expectedRef = "local-ref:" + cryptoService.sha256Fingerprint(
                    hmac.getBytes(java.nio.charset.StandardCharsets.UTF_8));
            verified = java.security.MessageDigest.isEqual(
                    expectedRef.getBytes(java.nio.charset.StandardCharsets.UTF_8),
                    credential.getBytes(java.nio.charset.StandardCharsets.UTF_8));
            details = verified
                    ? "LOCAL mode auto-verified — reference token matched"
                    : "LOCAL mode reference token mismatch";
        } else {
            verified = verifyCredential(session, method, credential);
            details = verified
                    ? method + " signature verified against challenge nonce"
                    : method + " signature mismatch";
        }

        session.setIdentityVerified(verified);
        if (verified) {
            session.setVerifiedSubject(session.getClientId());
        }

        return new ToolResult.Success(formatResult(handshakeId, method, verified, session.getClientId(), details));
    }

    private ToolResult executeHttpClient(String handshakeId, String method, String credential) {
        HandshakeSession session = sessionStore.require(handshakeId);

        // Send signature to MCP server for verification
        String response = httpClient.post("/verify", Map.of(
                "handshakeId", handshakeId,
                "method", method,
                "credential", credential
        ));

        // Parse server response
        try {
            var mapper = new com.fasterxml.jackson.databind.ObjectMapper();
            var node = mapper.readTree(response);
            boolean verified = node.get("verified").asBoolean();

            session.setIdentityVerified(verified);
            if (verified) {
                session.setVerifiedSubject(session.getClientId());
            }

            return new ToolResult.Success(response);
        } catch (Exception e) {
            return new ToolResult.Error("Failed to parse verify response: " + e.getMessage());
        }
    }

    private ToolResult executeOrchestrated(String handshakeId, String method, String credential,
                                           Map<String, Object> parameters) {
        HandshakeSession session = sessionStore.require(handshakeId);

        // Check if MCP server has already verified
        Object serverVerified = parameters.get("serverVerified");
        if (serverVerified != null) {
            boolean verified = Boolean.parseBoolean(serverVerified.toString());
            session.setIdentityVerified(verified);
            if (verified) {
                session.setVerifiedSubject(session.getClientId());
            }
            return new ToolResult.Success(formatResult(handshakeId, method, verified,
                    session.getClientId(),
                    verified ? "MCP server confirmed identity" : "MCP server rejected identity"));
        }

        // Return instructions for LLM
        return new ToolResult.Success(String.format("""
                {
                  "handshakeId": "%s",
                  "method": "%s",
                  "credential": "%s",
                  "mode": "ORCHESTRATED",
                  "instructions": "Send this credential to the MCP server's verify endpoint. Then call this tool again with the serverVerified result."
                }""",
                handshakeId, method, credential));
    }

    private boolean verifyCredential(HandshakeSession session, String method, String credential) {
        if ("HMAC-SHA256".equalsIgnoreCase(method) || "JWT".equalsIgnoreCase(method)) {
            return cryptoService.hmacVerify(
                    session.getSharedSecret(), session.getChallengeNonce(), credential);
        }
        return false;
    }

    private String formatResult(String handshakeId, String method, boolean verified,
                                String clientId, String details) {
        return String.format("""
                {
                  "handshakeId": "%s",
                  "authMethod": "%s",
                  "verified": %s,
                  "subject": %s,
                  "verificationDetails": "%s"
                }""",
                handshakeId, method, verified,
                verified ? "\"" + clientId + "\"" : "null",
                details);
    }
}
