#!/usr/bin/env bash
#
# JaiClaw Docker Auth Directory Mapping — generates volume mounts for OAuth credential directories
#
# Maps provider names to host directories containing credentials that Docker containers need.
# Generates a docker-compose override file with read-only volume mounts.
#
# Usage (sourced by start.sh):
#   source scripts/lib/docker-auth-dirs.sh
#   generate_auth_volumes_override "/path/to/output.yml" "gateway"
#
# Configuration:
#   JAICLAW_DOCKER_AUTH_DIRS — comma-separated list of dirs to mount (default: "auto")
#     "all"    — mount all known auth directories that exist
#     "none"   — skip auth directory mounting
#     "auto"   — mount only dirs that exist on the host (default)
#     custom   — comma-separated: "claude,codex,jaiclaw"
#

# Provider-to-directory mapping (from AuthProfileConstants)
# Format: provider_key|host_dir|container_dir
AUTH_DIR_MAPPINGS=(
    "jaiclaw|$HOME/.jaiclaw|/home/jboss/.jaiclaw"
    "claude|$HOME/.claude|/home/jboss/.claude"
    "codex|$HOME/.codex|/home/jboss/.codex"
    "qwen|$HOME/.qwen|/home/jboss/.qwen"
    "minimax|$HOME/.minimax|/home/jboss/.minimax"
)

# Resolve which auth directories to mount
# Returns newline-separated "host_dir:container_dir:ro" strings
resolve_auth_mounts() {
    local mode="${JAICLAW_DOCKER_AUTH_DIRS:-auto}"
    local mounts=()

    case "$mode" in
        none)
            return
            ;;
        all)
            for mapping in "${AUTH_DIR_MAPPINGS[@]}"; do
                IFS='|' read -r key host_dir container_dir <<< "$mapping"
                if [ -d "$host_dir" ]; then
                    mounts+=("${host_dir}:${container_dir}:ro")
                fi
            done
            ;;
        auto)
            for mapping in "${AUTH_DIR_MAPPINGS[@]}"; do
                IFS='|' read -r key host_dir container_dir <<< "$mapping"
                if [ -d "$host_dir" ]; then
                    mounts+=("${host_dir}:${container_dir}:ro")
                fi
            done
            ;;
        *)
            # Comma-separated provider keys
            IFS=',' read -ra requested <<< "$mode"
            for req in "${requested[@]}"; do
                req=$(echo "$req" | tr -d '[:space:]')
                for mapping in "${AUTH_DIR_MAPPINGS[@]}"; do
                    IFS='|' read -r key host_dir container_dir <<< "$mapping"
                    if [ "$key" = "$req" ] && [ -d "$host_dir" ]; then
                        mounts+=("${host_dir}:${container_dir}:ro")
                    fi
                done
            done
            ;;
    esac

    for m in "${mounts[@]}"; do
        echo "$m"
    done
}

# Generate a docker-compose override YAML file with auth volume mounts
# Usage: generate_auth_volumes_override <output_file> <service_name>
generate_auth_volumes_override() {
    local output_file="$1"
    local service_name="${2:-gateway}"

    local mounts
    mounts=$(resolve_auth_mounts)

    if [ -z "$mounts" ]; then
        # No mounts needed — remove override file if it exists
        rm -f "$output_file"
        return 1
    fi

    # Generate YAML
    cat > "$output_file" << EOF
# Auto-generated by JaiClaw — DO NOT EDIT
# Maps host OAuth credential directories into the container (read-only)
services:
  ${service_name}:
    volumes:
EOF

    while IFS= read -r mount; do
        echo "      - ${mount}" >> "$output_file"
    done <<< "$mounts"

    return 0
}
