package io.jclaw.shell.commands.setup.config;

import io.jclaw.shell.commands.setup.OnboardResult;
import org.springframework.stereotype.Component;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

@Component
public class EnvFileWriter {

    public String generate(OnboardResult result) {
        StringBuilder sb = new StringBuilder();
        sb.append("# JClaw secrets - generated by setup wizard\n");
        sb.append("# Source this file before running JClaw: source ").append(
                ConfigLocation.envFile(result.configDir())).append("\n\n");

        // Security
        sb.append("# Security\n");
        sb.append("export JCLAW_SECURITY_MODE=").append(result.securityMode()).append("\n");
        if ("api-key".equals(result.securityMode()) && result.apiKey() != null && !result.apiKey().isBlank()) {
            sb.append("export JCLAW_API_KEY=").append(result.apiKey()).append("\n");
        }
        sb.append("\n");

        // LLM provider key
        if (result.llmApiKey() != null && !result.llmApiKey().isBlank()) {
            String envVar = switch (result.llmProvider()) {
                case "openai" -> "OPENAI_API_KEY";
                case "anthropic" -> "ANTHROPIC_API_KEY";
                default -> null;
            };
            if (envVar != null) {
                sb.append("export ").append(envVar).append("=").append(result.llmApiKey()).append("\n");
            }
        }

        // Telegram
        OnboardResult.TelegramConfig tg = result.telegram();
        if (tg != null && tg.enabled()) {
            sb.append("\n# Telegram\n");
            sb.append("export TELEGRAM_ENABLED=true\n");
            sb.append("export TELEGRAM_BOT_TOKEN=").append(tg.botToken()).append("\n");
        }

        // Slack
        OnboardResult.SlackConfig slack = result.slack();
        if (slack != null && slack.enabled()) {
            sb.append("\n# Slack\n");
            sb.append("export SLACK_ENABLED=true\n");
            sb.append("export SLACK_BOT_TOKEN=").append(slack.botToken()).append("\n");
            sb.append("export SLACK_SIGNING_SECRET=").append(slack.signingSecret()).append("\n");
            if (slack.appToken() != null && !slack.appToken().isBlank()) {
                sb.append("export SLACK_APP_TOKEN=").append(slack.appToken()).append("\n");
            }
        }

        // Discord
        OnboardResult.DiscordConfig discord = result.discord();
        if (discord != null && discord.enabled()) {
            sb.append("\n# Discord\n");
            sb.append("export DISCORD_ENABLED=true\n");
            sb.append("export DISCORD_BOT_TOKEN=").append(discord.botToken()).append("\n");
            sb.append("export DISCORD_APPLICATION_ID=").append(discord.applicationId()).append("\n");
        }

        // MCP server auth tokens
        if (result.mcpServers() != null) {
            for (OnboardResult.McpServerConfig mcp : result.mcpServers()) {
                if (mcp.authToken() != null && !mcp.authToken().isBlank()) {
                    String envVar = "MCP_" + mcp.name().toUpperCase().replace("-", "_") + "_TOKEN";
                    sb.append("\n# MCP Server: ").append(mcp.name()).append("\n");
                    sb.append("export ").append(envVar).append("=").append(mcp.authToken()).append("\n");
                }
            }
        }

        return sb.toString();
    }

    public void write(OnboardResult result) throws IOException {
        Path dir = result.configDir();
        Files.createDirectories(dir);
        Path file = ConfigLocation.envFile(dir);
        Files.writeString(file, generate(result));
    }
}
