package io.jaiclaw.shell.commands.setup.config;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.dataformat.yaml.YAMLFactory;
import com.fasterxml.jackson.dataformat.yaml.YAMLGenerator;
import com.fasterxml.jackson.dataformat.yaml.YAMLMapper;
import io.jaiclaw.config.JaiClawProperties;
import io.jaiclaw.config.ModelsProperties.ModelProviderConfig;
import io.jaiclaw.shell.commands.setup.OnboardResult;
import io.jaiclaw.shell.commands.setup.OnboardResult.McpServerConfig;
import io.jaiclaw.shell.commands.setup.OnboardResult.McpTransportType;
import io.jaiclaw.shell.commands.setup.OnboardResult.SkillsConfig;
import org.springframework.stereotype.Component;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

@Component
public class YamlConfigWriter {

    private final JaiClawProperties jaiClawProperties;

    public YamlConfigWriter(JaiClawProperties jaiClawProperties) {
        this.jaiClawProperties = jaiClawProperties;
    }

    private static final YAMLMapper MAPPER = YAMLMapper.builder(
            YAMLFactory.builder()
                    .disable(YAMLGenerator.Feature.WRITE_DOC_START_MARKER)
                    .enable(YAMLGenerator.Feature.MINIMIZE_QUOTES)
                    .build())
            .disable(JsonGenerator.Feature.AUTO_CLOSE_TARGET)
            .build();

    public String generate(OnboardResult result) throws IOException {
        var root = new LinkedHashMap<String, Object>();

        root.put("jaiclaw", buildJclawSection(result));
        root.put("spring", buildSpringSection(result));

        if (result.isManual()) {
            root.put("server", buildServerSection(result));
        }

        return "# JaiClaw configuration - generated by setup wizard\n"
                + MAPPER.writeValueAsString(root);
    }

    public void write(OnboardResult result) throws IOException {
        Path dir = result.configDir();
        Files.createDirectories(dir);
        Path file = ConfigLocation.yamlFile(dir);
        Files.writeString(file, generate(result));
    }

    private Map<String, Object> buildJclawSection(OnboardResult result) {
        var jaiclaw = new LinkedHashMap<String, Object>();

        // identity
        jaiclaw.put("identity", Map.of("name", result.assistantName()));

        // security
        jaiclaw.put("security", buildSecuritySection(result));

        // agent
        var defaultAgent = new LinkedHashMap<String, Object>();
        var model = new LinkedHashMap<String, Object>();
        model.put("primary", result.llmModel());
        String fallback = null;
        ModelProviderConfig providerConfig = jaiClawProperties.models().providers().get(result.llmProvider());
        if (providerConfig != null) {
            fallback = providerConfig.fallbackModel();
        }
        if (fallback != null) {
            model.put("fallbacks", List.of(fallback));
        }
        defaultAgent.put("model", model);
        defaultAgent.put("tools", Map.of("profile", "coding"));

        var agent = new LinkedHashMap<String, Object>();
        agent.put("default-agent", "default");
        agent.put("agents", Map.of("default", defaultAgent));
        jaiclaw.put("agent", agent);

        // tools
        jaiclaw.put("tools", Map.of("profile", "coding"));

        // skills
        jaiclaw.put("skills", buildSkillsSection(result));

        // plugins
        jaiclaw.put("plugins", Map.of("enabled", true));

        // mcp-servers
        var mcpServers = buildMcpServersSection(result);
        if (mcpServers != null) {
            jaiclaw.put("mcp-servers", mcpServers);
        }

        // channels
        var channels = buildChannelsSection(result);
        if (channels != null) {
            jaiclaw.put("channels", channels);
        }

        return jaiclaw;
    }

    private Map<String, Object> buildSkillsSection(OnboardResult result) {
        var skills = new LinkedHashMap<String, Object>();
        SkillsConfig cfg = result.skillsConfig();
        if (cfg != null && cfg.enabledBundled() != null) {
            skills.put("allow-bundled", cfg.enabledBundled());
        } else {
            skills.put("allow-bundled", List.of("*"));
        }
        if (cfg != null && cfg.workspaceDir() != null) {
            skills.put("workspace-dir", cfg.workspaceDir());
        }
        return skills;
    }

    private Map<String, Object> buildMcpServersSection(OnboardResult result) {
        List<McpServerConfig> servers = result.mcpServers();
        if (servers == null || servers.isEmpty()) {
            return null;
        }
        var section = new LinkedHashMap<String, Object>();
        for (McpServerConfig server : servers) {
            var entry = new LinkedHashMap<String, Object>();
            entry.put("type", server.transportType().name().toLowerCase());
            if (server.description() != null) {
                entry.put("description", server.description());
            }
            if (server.transportType() == McpTransportType.STDIO) {
                entry.put("command", server.command());
                if (server.args() != null && !server.args().isEmpty()) {
                    entry.put("args", server.args());
                }
            } else {
                entry.put("url", server.url());
                if (server.authToken() != null) {
                    String envVar = "MCP_" + server.name().toUpperCase().replace("-", "_") + "_TOKEN";
                    entry.put("auth-token", "${" + envVar + "}");
                }
            }
            section.put(server.name(), entry);
        }
        return section;
    }

    private Map<String, Object> buildChannelsSection(OnboardResult result) {
        var channels = new LinkedHashMap<String, Object>();

        OnboardResult.TelegramConfig tg = result.telegram();
        if (tg != null && tg.enabled()) {
            var telegram = new LinkedHashMap<String, Object>();
            telegram.put("enabled", true);
            telegram.put("bot-token", "${TELEGRAM_BOT_TOKEN}");
            channels.put("telegram", telegram);
        }

        OnboardResult.SlackConfig slack = result.slack();
        if (slack != null && slack.enabled()) {
            var slackMap = new LinkedHashMap<String, Object>();
            slackMap.put("enabled", true);
            slackMap.put("bot-token", "${SLACK_BOT_TOKEN}");
            slackMap.put("signing-secret", "${SLACK_SIGNING_SECRET}");
            if (slack.appToken() != null && !slack.appToken().isBlank()) {
                slackMap.put("app-token", "${SLACK_APP_TOKEN}");
            }
            channels.put("slack", slackMap);
        }

        OnboardResult.DiscordConfig discord = result.discord();
        if (discord != null && discord.enabled()) {
            var discordMap = new LinkedHashMap<String, Object>();
            discordMap.put("enabled", true);
            discordMap.put("bot-token", "${DISCORD_BOT_TOKEN}");
            discordMap.put("application-id", "${DISCORD_APPLICATION_ID}");
            channels.put("discord", discordMap);
        }

        return channels.isEmpty() ? null : channels;
    }

    private Map<String, Object> buildSpringSection(OnboardResult result) {
        var ai = new LinkedHashMap<String, Object>();
        switch (result.llmProvider()) {
            case "openai" -> ai.put("openai", Map.of("api-key", "${OPENAI_API_KEY}"));
            case "anthropic" -> ai.put("anthropic", Map.of("api-key", "${ANTHROPIC_API_KEY}"));
            case "ollama" -> ai.put("ollama", Map.of("base-url", result.ollamaBaseUrl()));
            case "bedrock" -> {
                var converse = new LinkedHashMap<String, Object>();
                converse.put("enabled", true);
                var bedrockAws = new LinkedHashMap<String, Object>();
                bedrockAws.put("region", result.awsRegion());
                ai.put("bedrock", Map.of("converse", converse, "aws", bedrockAws));
            }
        }
        return Map.of("ai", ai);
    }

    private Map<String, Object> buildSecuritySection(OnboardResult result) {
        var security = new LinkedHashMap<String, Object>();
        security.put("mode", result.securityMode());
        if ("api-key".equals(result.securityMode()) && result.apiKey() != null) {
            security.put("api-key", "${JAICLAW_API_KEY}");
        }
        return security;
    }

    private Map<String, Object> buildServerSection(OnboardResult result) {
        var server = new LinkedHashMap<String, Object>();
        server.put("port", result.serverPort());
        server.put("address", result.bindAddress());
        return server;
    }
}
